apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sql
        image: mysql:oracle
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: sql-credentials
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sql-credentials
              key: DB_PASSWORD
        - name: MYSQL_DATABASE
          value: mydb
